### ISSUE TITLE
What happened to the read_sensortag_CC2650.py example

### ISSUE THREAD

**Issue by NickWaterton** [ukBaz/python-bluezero#162]
I was looking for a sensortag python program. This looked promising, but just - not there?

**Comment by ukBaz** [comment]
Hi @NickWaterton ,

Through the power of revision control it is still available:
https://github.com/ukBaz/python-bluezero/blob/786611f09f0f50ff09b64f64b7ba9c58de0339a1/examples/level10/read_sensortag_CC2650.py

It has been removed from the master branch going forward because it was proving too difficult to keep up to date whrn the API changed on Bluezero and on software updates to the Sensor Tags. This was all compounded by no automatic testing for the examples.

If I was to start again I would base the Sensor Tag example on the Microbit class in microbit.py:
https://github.com/ukBaz/python-bluezero/blob/master/bluezero/microbit.py
which makes use of the Bluezero central.py file.

I am going to close this ticket but please open a new one if you have questions about implementing a some Senor Tag code.
