### ISSUE TITLE
get_gatt_manager_interface() and get_advert_manager_interface() missing from tools

### ISSUE THREAD

**Issue by nathan-leung** [ukBaz/python-bluezero#197]
peripheral.py tries to call `tools.get_advert_manager_interface()` and `tools.get_gatt_manager_interface()` when these functions do not exist in the tools module. Am I missing something here?

**Comment by ukBaz** [comment]
The `peripheral.py` file is in need of a rewrite as I found when started looking at creating a new peripheral example in the https://github.com/ukBaz/python-bluezero/tree/ble_uart branch.

I did a quick fix in that branch for this issue:
https://github.com/ukBaz/python-bluezero/commit/39ad70fdbb51046799a998109bbfdaaf70670768#diff-506182f40f22986d78be9d8c28fddc8aL233

I had been holding off merging the fixes in because I wanted to do a proper fix of `peripheral.py` rather than a quick a dirty fix. However that isn't progressing as quickly as I had hoped.

What are you trying to do?
Do you want to take a look at ble_uart branch to see if that works for you?
